<a href="https://colab.research.google.com/github/Rishikesh400/Word-Embedding-Using-Keras/blob/master/Word_Embedding_Using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
## Vocabulary Size
vocab_size = 10000

## One Hot Repressentation

In [ ]:
onehot_repr = [one_hot(words, vocab_size) for words in sent]
onehot_repr

[[566, 8775, 4521, 9803],
 [566, 8775, 4521, 4250],
 [566, 4445, 4521, 3916],
 [7429, 1799, 8081, 1617, 6134],
 [7429, 1799, 8081, 1617, 7356],
 [1129, 566, 5557, 4521, 5155],
 [3779, 9749, 4287, 1617]]

## Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd

In [ ]:
sent_len = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0,  566, 8775, 4521, 9803],
       [   0,    0,    0,    0,  566, 8775, 4521, 4250],
       [   0,    0,    0,    0,  566, 4445, 4521, 3916],
       [   0,    0,    0, 7429, 1799, 8081, 1617, 6134],
       [   0,    0,    0, 7429, 1799, 8081, 1617, 7356],
       [   0,    0,    0, 1129,  566, 5557, 4521, 5155],
       [   0,    0,    0,    0, 3779, 9749, 4287, 1617]], dtype=int32)

In [ ]:
dim = 10
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_len))

In [ ]:
model.compile('adam', 'mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(embedded_docs)

array([[[ 1.66551583e-02,  3.68668549e-02,  4.17758934e-02,
         -4.38378714e-02,  2.73418166e-02, -5.96940517e-04,
         -1.09693184e-02,  2.11727284e-02, -3.29113975e-02,
          1.26126297e-02],
        [ 1.66551583e-02,  3.68668549e-02,  4.17758934e-02,
         -4.38378714e-02,  2.73418166e-02, -5.96940517e-04,
         -1.09693184e-02,  2.11727284e-02, -3.29113975e-02,
          1.26126297e-02],
        [ 1.66551583e-02,  3.68668549e-02,  4.17758934e-02,
         -4.38378714e-02,  2.73418166e-02, -5.96940517e-04,
         -1.09693184e-02,  2.11727284e-02, -3.29113975e-02,
          1.26126297e-02],
        [ 1.66551583e-02,  3.68668549e-02,  4.17758934e-02,
         -4.38378714e-02,  2.73418166e-02, -5.96940517e-04,
         -1.09693184e-02,  2.11727284e-02, -3.29113975e-02,
          1.26126297e-02],
        [-2.19113231e-02,  3.68306674e-02,  1.99149884e-02,
         -7.58150965e-03, -3.92387509e-02,  1.13230124e-02,
          6.94161654e-03,  4.54758294e-02, -7.184255

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,  566, 8775, 4521, 9803], dtype=int32)

In [ ]:
## All the above values of embedded_docs[0] are converted into dimension of 10 vectors
model.predict(embedded_docs)[0]

array([[ 0.01665516,  0.03686685,  0.04177589, -0.04383787,  0.02734182,
        -0.00059694, -0.01096932,  0.02117273, -0.0329114 ,  0.01261263],
       [ 0.01665516,  0.03686685,  0.04177589, -0.04383787,  0.02734182,
        -0.00059694, -0.01096932,  0.02117273, -0.0329114 ,  0.01261263],
       [ 0.01665516,  0.03686685,  0.04177589, -0.04383787,  0.02734182,
        -0.00059694, -0.01096932,  0.02117273, -0.0329114 ,  0.01261263],
       [ 0.01665516,  0.03686685,  0.04177589, -0.04383787,  0.02734182,
        -0.00059694, -0.01096932,  0.02117273, -0.0329114 ,  0.01261263],
       [-0.02191132,  0.03683067,  0.01991499, -0.00758151, -0.03923875,
         0.01132301,  0.00694162,  0.04547583, -0.00718426,  0.02677883],
       [ 0.00727301,  0.04689639,  0.04838607, -0.03461377, -0.00760275,
        -0.01536433, -0.0448086 , -0.03823104,  0.0017738 ,  0.03672745],
       [ 0.04554209, -0.02811769,  0.0262563 , -0.04067181, -0.03917683,
        -0.02016616, -0.04699389, -0.00593567